### ISSUE TITLE
Can not create edge with nonexistent target

### ISSUE THREAD

**Issue by physics515** [tone-row/flowchart-fun#236] opened 2022-02-04 16:50 UTC
I'm in a situation with my current chart where it resolves fine, I add a new line to the chart with no references and get the error below:
![image](https://user-images.githubusercontent.com/7359379/152568362-98b62344-d3fb-40e8-9c28-75cbafd44604.png)

I'm not sure what is going on here. Is there a limit to the number of nodes in a single chart?

I'd be willing to share the chart with you if you would like, it's hosted (but I don't want to post the link publicly).

**Comment by rob-gordon** [comment] 2022-02-04 18:02
@physics515 I have seen this issue and have a bug ticket for it. I'm hoping to get to it next week. Is it breaking somewhere around the ~150 nodes mark for you?

**Comment by physics515** [comment] 2022-02-04 18:16
That's probably about right. 173 lines w/ some comments.

**Comment by rob-gordon** [comment] 2022-02-10 17:13
Hey @physics515 ! Hoping to get this fixed today but I'm having trouble reproducing it now. Any chance you could send me a link to the graph that caused this error for you? You can email it to me (rob.gordon@tone-row.com) if you prefer.

**Comment by rob-gordon** [comment] 2022-02-11 14:26
@physics515 Thank you! I was able to fix it. It's on our dev brach but will merge to main this weekend. Our dev branch is running here if you need to use it sooner - https://dev.flowchart.fun/ Thanks for opening this issue! I'll close it once it merges.

**Comment by physics515** [comment] 2022-02-11 16:04
Awesome, just an fyi, I tried to login to the dev branch, and it gives me an error about not being a sponsor. I don't know if that is the correct behavior or not.

I don't need it until next week anyway, I was just wanting to play with it. :)

**Comment by rob-gordon** [comment] 2022-02-13 22:27
> Awesome, just an fyi, I tried to login to the dev branch, and it gives me an error about not being a sponsor. I don't know if that is the correct behavior or not.

That's expected for now. I want to discourage people from using `dev` in general because I can't always guarantee it will be in a good state.

The changes just merged. I tested your sample on https://flowchart.fun and it's working as expected now. Sorry for the inconvenience and thanks for making the issue!

**Closed by rob-gordon** 2022-02-13 22:27 UTC

**Comment by physics515** [comment] 2022-03-12 05:06
Thank you! Sorry it took so long to reply. But it was working the day you said it would.
